### ISSUE TITLE
SPLASH SCREEN: Layout Bug on Samsung Galaxy S6 - See image

### ISSUE THREAD

**Issue by ProdigyTech** [CSUMB-SP17-CST499/myMonte#54]

**Comment by ProdigyTech** [comment]
![screenshot_20170401-130313](https://cloud.githubusercontent.com/assets/8797862/24583748/fe95ae18-1709-11e7-8f88-fadf88683d69.png)

**Comment by aymswick** [comment]
Fixed in latest build.
